name: "Submit to Web Stores"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: Install dependencies
        run: npm run install:extension 
      - name: Build
        run: npm run build
      - name: Zip up release
        run: zip -r AlgoSigner.zip ./dist/*
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          artifact: ./AlgoSigner.zip
          keys: ${{ secrets.SUBMIT_KEYS }}
